
http://localhost:5000/api/products

###

POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name": "Strawberry and Elderflower Sorbet",
    "g": "false",
    "v": "true",
    "active": "true"
}
