version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
steps:
  - run:
    name: change dir
    command: |
      cd client
  - run:
    name: install dependencies
    command: |
      npm install
